typography_spectrum: 0.4936365771573037
color:
  brandStrength: 0.23161293589510024
  lightness: 0.8459559835027903
  saturation: 0.49290822609327734
  rhythmicContrast: 0.30381435924209654
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
layout_spectrum: 0.8362963565159589
author:
  name: David B. Cohen
  email: ravdbc@gmail.com
name: David B. Cohen
navigation:
  - name: Congregation Sinai Web Site
    url: 'http://www.congregationsinai.org'
    type: external
title: Wedding Hours Before Hurricane Katrina
description: 'As Yemeni Cab Drivers Pass By, Shouting, "Mazal Tov!"'
